import Logo from "@/shared/icons/Logo.svg"
import IcHeader from "@/shared/icons/ic_header.svg"
import IcUser from "@/shared/icons/user.svg"
import IcLocation  from "@/shared/icons/location.svg"
import IcServer from "@/shared/icons/Server.svg"
import IcMain from "@/shared/icons/ic_main.svg"
import IcSuc from "@/shared/icons/ic_succes.svg"
import IcFree from "@/shared/icons/Free.svg"
import IcCorrect from "@/shared/icons/correct.svg"
import IcGlobal from "@/shared/icons/Huge Global.svg"
import IcSponsored from "@/shared/icons/Sponsored.svg"
import IcAvatar1 from "@/shared/icons/avatar1.svg"
import IcAvatar2 from "@/shared/icons/avatar2.svg"
import IcAvatar3 from "@/shared/icons/avatar3.svg"
import IcStar from "@/shared/icons/star.svg"
export {Logo, IcHeader, IcUser, IcLocation, IcServer, IcMain, IcSuc, IcFree, IcCorrect, IcGlobal, IcSponsored, IcAvatar1, IcAvatar2, IcAvatar3, IcStar }
